apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-example-worker-app
  labels: 
    app: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-example-worker-app
  template:
    metadata:
      labels:
        app: docker-example-worker-app
    spec:
      containers:
      - name: worker
        image: docker/example-voting-app-worker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"