apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    app: results
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: docker-example-results-app
  ports:
  - port: 80