apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: docker-example-voting-app
  ports:
  - port: 80