apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting
  namespace: vote
spec:
  type: NodePort
  selector:
    app: docker-example-voting-app
  ports:
    - targetPort: 80
      port: 8082