apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    app: results
  namespace: vote
spec:
  type: NodePort
  selector:
    app: docker-example-results-app
  ports:
    - targetPort: 80
      port: 8081
